"""add face_images field to student

Revision ID: c5fd437851c9
Revises: 
Create Date: 2025-07-19 15:49:16.934955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fd437851c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_student')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_images', sa.Text(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('face_images')

    op.create_table('_alembic_tmp_student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rfid_tag', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('suffix', sa.VARCHAR(length=10), nullable=True),
    sa.Column('parent_contact', sa.VARCHAR(length=20), nullable=False),
    sa.Column('enrollment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('face_encoding', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_tag'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
